### ISSUE TITLE
Draft of book's core package (Zipfs Law)

### ISSUE THREAD

**Issue by lwjohnst86** [merely-useful/r-rse#54]
No need to have too much done on it, mostly to get an idea of what it will look like. For now, a repo in merely-useful is fine.

**Comment by cwickham** [comment]
I have a draft up at: https://github.com/merely-useful/zipfs

At this point it's probably useful to:
* review the [vignette](https://merely-useful.github.io/zipfs/articles/dracula.html), which runs through all the functionality, and
* glance over the body of the functions in [`R/`](https://github.com/merely-useful/zipfs/tree/main/R)

Some notes:

- In terms of interface and implementation I assumed a tidyverse style approach, but at the same time avoiding having to deal with any tidy evaluation.  This means the body of functions use things like stringr, tibble, ggplot2 and the pipe.  

- [`book_meta()`](https://github.com/merely-useful/zipfs/blob/main/R/book-meta.R) didn't exist in the Python version, but it basically implements some of the things explored in the Shell chapters of py-rse.  It might be a good candidate for introducing functions (and testing), since the body is relatively straight-forward.

- My word counts for Dracula don't quite match those in py-rse...any thoughts on why?

- I thought a little about how this relates to the realistic task of applying this to many books in a directory.  For now, I've put the books from py-rse in `inst/extdata` and some incomplete notes in [`dev/many-books.Rmd`](https://github.com/merely-useful/zipfs/blob/main/dev/many-books.Rmd).  

## Questions for Discussion

I think everything is up for discussion at this point, but some particular questions might be:
* Does the overall interface look OK? I.e. is this too many/too few functions? Are these the right names for the functions? Are the argument names and types OK? Are the output types OK?
* How do you feel about the complexity of the body of the functions?

**Comment by cwickham** [comment]
Realized discussion is probably better handled in the draft repo.  I've opened an issue at: https://github.com/merely-useful/zipfs/issues/1
